In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv(r'C:\Users\Nithya\Documents\ML\ml-100k\u.item',sep="|",encoding="latin-1")
movies.head()

movieId              title      release   x  \
0        1   Toy Story (1995)  01-Jan-1995 NaN   
1        2   GoldenEye (1995)  01-Jan-1995 NaN   
2        3  Four Rooms (1995)  01-Jan-1995 NaN   
3        4  Get Shorty (1995)  01-Jan-1995 NaN   
4        5     Copycat (1995)  01-Jan-1995 NaN   

                                                   y  0  0.1  0.2  1  1.1  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...  0    0    0  1    1   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...  0    1    1  0    0   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...  0    0    0  0    0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...  0    1    0  0    0   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)  0    0    0  0    0   

   ...  0.6  0.7  0.8  0.9  0.10  0.11  0.12  0.13  0.14  0.15  
0  ...    0    0    0    0     0     0     0     0     0     0  
1  ...    0    0    0    0     0     0     0     1     0     0  
2  ...    0    0    0    0     0     0     0     1     0     0  
3  ...    0    0    0    0     0     0     0     0     0     0  
4  ...    0    0    0    0     0     0     0     1     0     0  

[5 rows x 24 columns]

In [3]:

ratings = pd.read_csv(r'C:\Users\Nithya\Documents\ML\ml-100k\u.data',sep="\t",usecols=['userId','itemId','rating'])
ratings.head()

userId  itemId  rating
0     196     242       3
1     186     302       3
2      22     377       1
3     244      51       2
4     166     346       1

In [21]:
row=max(ratings.userId)
row

943

In [25]:
col=max(ratings.itemId)
col

1682

In [6]:
arr=np.zeros([row,col],dtype=int)

In [7]:
print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
for i in range(0,100000):
    arr[ratings.userId[i]-1][ratings.itemId[i]-1]=ratings.rating[i]

In [9]:
print(arr)

[[5 3 4 ... 0 0 0]
 [4 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [5 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]]


In [10]:
euclArr = np.zeros([row,row],dtype=object)

In [11]:
for i in range(0,row):
    for j in range(0,row):
        dist = np.linalg.norm(arr[i]-arr[j])
        euclArr[i][j] = (dist,j)

In [12]:
for i in range(0,row):
    euclArr[i].sort(axis=0)

In [13]:
euclArr

array([[(0.0, 0), (55.06359959174482, 737), (55.235857918565905, 520),
        ..., (81.17881497040962, 12), (82.84926070883192, 415),
        (85.37564055396598, 449)],
       [(0.0, 1), (25.632011235952593, 700), (28.0178514522438, 265),
        ..., (84.4866853415377, 415), (84.6994687114388, 6),
        (90.08329478876757, 449)],
       [(0.0, 2), (20.952326839756964, 316), (21.354156504062622, 655),
        ..., (84.35045939412541, 12), (87.46999485537883, 415),
        (92.32551110067033, 449)],
       ...,
       [(0.0, 940), (20.71231517720798, 741), (20.760539492026695, 440),
        ..., (86.02906485601247, 12), (87.66413177577246, 415),
        (92.2496612459905, 449)],
       [(0.0, 941), (37.16180835212409, 162), (37.52332607858744, 855),
        ..., (82.8190799272728, 12), (85.38735269347563, 415),
        (86.79861750051091, 449)],
       [(0.0, 942), (43.3589667773576, 932), (43.86342439892262, 773),
        ..., (80.16857239592083, 415), (80.77747210701756, 12),
     

In [14]:
k_val = eval(input("value of k : "))

value of k : 20


In [15]:
tmpList = []
for i in range(0,k_val):
    tmpList+=[euclArr[0][i]]


In [16]:
tmpList

[(0.0, 0),
 (55.06359959174482, 737),
 (55.235857918565905, 520),
 (55.614746245937326, 932),
 (57.0701322935211, 714),
 (57.40209055426466, 43),
 (57.463031594234565, 867),
 (57.51521537819362, 772),
 (57.61076288333631, 214),
 (57.62811813689564, 773),
 (57.645468165329355, 267),
 (57.86190456595773, 296),
 (57.879184513951124, 76),
 (58.06031346797914, 915),
 (58.180752831155424, 507),
 (58.19793810780585, 537),
 (58.215118311311535, 197),
 (58.22370651203855, 176),
 (58.283788483591216, 659),
 (58.360945845659494, 805)]

In [20]:
tmpList[1][1]



737

In [26]:
movRating=0
c = 0
for i in range(0,col):
    if(arr[0][i] == 0):
        for j in range(0,k_val):
            if(arr[tmpList[j][1]][i] !=0):
                c+=1
                movRating+=arr[tmpList[j][1]][i]
        if(c!=0 and round(movRating/c,2)>=2.5):
            print("Movie : ",i,"predicted rating : ",round(movRating/c,2))
        movRating=0
        c=0
            

Movie :  272 predicted rating :  3.2
Movie :  273 predicted rating :  3.5
Movie :  274 predicted rating :  4.5
Movie :  275 predicted rating :  3.0
Movie :  276 predicted rating :  3.0
Movie :  279 predicted rating :  2.5
Movie :  280 predicted rating :  3.0
Movie :  281 predicted rating :  3.0
Movie :  282 predicted rating :  4.0
Movie :  283 predicted rating :  3.0
Movie :  285 predicted rating :  4.0
Movie :  287 predicted rating :  3.25
Movie :  289 predicted rating :  3.25
Movie :  291 predicted rating :  3.0
Movie :  293 predicted rating :  3.0
Movie :  297 predicted rating :  2.89
Movie :  298 predicted rating :  4.0
Movie :  299 predicted rating :  2.5
Movie :  300 predicted rating :  3.5
Movie :  301 predicted rating :  4.25
Movie :  306 predicted rating :  3.2
Movie :  312 predicted rating :  4.5
Movie :  314 predicted rating :  4.0
Movie :  315 predicted rating :  4.0
Movie :  316 predicted rating :  4.17
Movie :  317 predicted rating :  4.08
Movie :  323 predicted rating : 

Movie :  1069 predicted rating :  3.0
Movie :  1070 predicted rating :  3.0
Movie :  1072 predicted rating :  3.67
Movie :  1073 predicted rating :  2.5
Movie :  1096 predicted rating :  4.0
Movie :  1097 predicted rating :  4.0
Movie :  1100 predicted rating :  4.0
Movie :  1108 predicted rating :  3.0
Movie :  1112 predicted rating :  4.0
Movie :  1116 predicted rating :  3.0
Movie :  1117 predicted rating :  3.0
Movie :  1118 predicted rating :  3.0
Movie :  1128 predicted rating :  3.0
Movie :  1134 predicted rating :  2.67
Movie :  1135 predicted rating :  3.0
Movie :  1141 predicted rating :  5.0
Movie :  1152 predicted rating :  4.0
Movie :  1168 predicted rating :  4.0
Movie :  1169 predicted rating :  3.0
Movie :  1186 predicted rating :  3.0
Movie :  1193 predicted rating :  4.0
Movie :  1205 predicted rating :  2.5
Movie :  1217 predicted rating :  3.5
Movie :  1219 predicted rating :  3.0
Movie :  1239 predicted rating :  3.5
Movie :  1243 predicted rating :  2.5
Movie :  1

In [28]:
# for specific user
userInput = eval(input("for a specific user 0-942: "))
tmpList = []
for i in range(userInput,k_val):
    tmpList+=[euclArr[userInput][i]]

movRating=0
c = 0
for i in range(0,col):
    if(arr[userInput][i] == 0):
        for j in range(0,k_val):
            if(arr[tmpList[j][1]][i] !=0):
                c+=1
                movRating+=arr[tmpList[j][1]][i]
        if(c!=0 and round(movRating/c,2)>=2.5):
            print("Movie : ",i,"predicted rating : ",round(movRating/c,2))
        movRating=0
        c=0

for a specific user 0-942: 0
Movie :  272 predicted rating :  3.2
Movie :  273 predicted rating :  3.5
Movie :  274 predicted rating :  4.5
Movie :  275 predicted rating :  3.0
Movie :  276 predicted rating :  3.0
Movie :  279 predicted rating :  2.5
Movie :  280 predicted rating :  3.0
Movie :  281 predicted rating :  3.0
Movie :  282 predicted rating :  4.0
Movie :  283 predicted rating :  3.0
Movie :  285 predicted rating :  4.0
Movie :  287 predicted rating :  3.25
Movie :  289 predicted rating :  3.25
Movie :  291 predicted rating :  3.0
Movie :  293 predicted rating :  3.0
Movie :  297 predicted rating :  2.89
Movie :  298 predicted rating :  4.0
Movie :  299 predicted rating :  2.5
Movie :  300 predicted rating :  3.5
Movie :  301 predicted rating :  4.25
Movie :  306 predicted rating :  3.2
Movie :  312 predicted rating :  4.5
Movie :  314 predicted rating :  4.0
Movie :  315 predicted rating :  4.0
Movie :  316 predicted rating :  4.17
Movie :  317 predicted rating :  4.08
Mov

Movie :  1020 predicted rating :  5.0
Movie :  1021 predicted rating :  4.0
Movie :  1035 predicted rating :  3.0
Movie :  1038 predicted rating :  4.0
Movie :  1041 predicted rating :  3.0
Movie :  1045 predicted rating :  2.5
Movie :  1046 predicted rating :  3.0
Movie :  1047 predicted rating :  3.0
Movie :  1049 predicted rating :  4.0
Movie :  1057 predicted rating :  4.0
Movie :  1062 predicted rating :  5.0
Movie :  1064 predicted rating :  3.0
Movie :  1066 predicted rating :  4.0
Movie :  1068 predicted rating :  4.0
Movie :  1069 predicted rating :  3.0
Movie :  1070 predicted rating :  3.0
Movie :  1072 predicted rating :  3.67
Movie :  1073 predicted rating :  2.5
Movie :  1096 predicted rating :  4.0
Movie :  1097 predicted rating :  4.0
Movie :  1100 predicted rating :  4.0
Movie :  1108 predicted rating :  3.0
Movie :  1112 predicted rating :  4.0
Movie :  1116 predicted rating :  3.0
Movie :  1117 predicted rating :  3.0
Movie :  1118 predicted rating :  3.0
Movie :  11

# ERROR PREDICTION


In [29]:
# for specific user
userInput = eval(input("for a specific user 0-942: "))
tmpList = []
for i in range(userInput,k_val):
    tmpList+=[euclArr[userInput][i]]

movRating=0
c = 0
for i in range(0,col):
    if(arr[userInput][i] != 0):
        for j in range(0,k_val):
            if(arr[tmpList[j][1]][i] !=0):
                c+=1
                movRating+=arr[tmpList[j][1]][i]
        if(c!=0 ):
            print("Movie : ",i,"error : ",abs(arr[userInput][i]-round(movRating/c,2)))
        movRating=0
        c=0

for a specific user 0-942: 0
Movie :  0 error :  1.1800000000000002
Movie :  1 error :  0.4500000000000002
Movie :  2 error :  1.7999999999999998
Movie :  3 error :  0.08999999999999986
Movie :  4 error :  0.33000000000000007
Movie :  5 error :  2.0
Movie :  6 error :  0.33000000000000007
Movie :  7 error :  1.33
Movie :  8 error :  0.5
Movie :  9 error :  0.5
Movie :  10 error :  1.46
Movie :  11 error :  0.6900000000000004
Movie :  12 error :  1.5
Movie :  13 error :  0.5
Movie :  14 error :  1.6
Movie :  15 error :  1.0
Movie :  16 error :  0.25
Movie :  17 error :  0.0
Movie :  18 error :  0.0
Movie :  19 error :  0.0
Movie :  20 error :  1.0
Movie :  21 error :  0.1499999999999999
Movie :  22 error :  0.0
Movie :  23 error :  0.27
Movie :  24 error :  1.38
Movie :  25 error :  0.0
Movie :  26 error :  0.16999999999999993
Movie :  27 error :  0.16999999999999993
Movie :  28 error :  0.8300000000000001
Movie :  29 error :  0.5
Movie :  30 error :  0.08999999999999986
Movie :  31 err

Movie :  267 error :  0.5999999999999996
Movie :  268 error :  1.2000000000000002
Movie :  269 error :  2.0
Movie :  270 error :  0.7799999999999998
Movie :  271 error :  0.75
